/**
 * IndexNow submission helper — push URLs to Bing, Yandex, Seznam, and Naver
 * instantly instead of waiting for regular crawl. Google does NOT consume
 * IndexNow; for Google use GSC's URL Inspection or rely on sitemap crawl.
 *
 * Required env vars (see .env.local / .env.example):
 *   SITE_URL        e.g. https://piedmontdentalbydesign.com (no trailing slash)
 *   INDEXNOW_KEY    Generated by scripts/generate-indexnow-key.mjs — the
 *                   matching key file must be live at `${SITE_URL}/${key}.txt`
 *                   (served from public/, see app/[indexNowKey].txt equivalent
 *                   static file already committed in public/).
 *
 * Usage — from a revalidation route or publish webhook:
 *
 *   import { submitToIndexNow } from "@/lib/indexnow";
 *
 *   await submitToIndexNow([`${process.env.SITE_URL}/blog/${slug}`]);
 */

export type IndexNowResult = {
  ok: boolean;
  status: number;
  submitted: number;
  message?: string;
};

export async function submitToIndexNow(urls: string[]): Promise<IndexNowResult> {
  const SITE_URL = process.env.SITE_URL?.replace(/\/$/, "");
  const INDEXNOW_KEY = process.env.INDEXNOW_KEY;

  if (!SITE_URL || !INDEXNOW_KEY) {
    return {
      ok: false,
      status: 0,
      submitted: 0,
      message: "Missing SITE_URL or INDEXNOW_KEY env vars",
    };
  }

  if (urls.length === 0) {
    return { ok: true, status: 200, submitted: 0, message: "No URLs to submit" };
  }

  const host = new URL(SITE_URL).host;

  // Reject cross-host URLs — IndexNow returns 422 otherwise
  const validUrls = urls.filter((u) => {
    try {
      return new URL(u).host === host;
    } catch {
      return false;
    }
  });

  if (validUrls.length === 0) {
    return {
      ok: false,
      status: 422,
      submitted: 0,
      message: `No URLs match host ${host}`,
    };
  }

  const body = {
    host,
    key: INDEXNOW_KEY,
    keyLocation: `${SITE_URL}/${INDEXNOW_KEY}.txt`,
    urlList: validUrls,
  };

  try {
    const res = await fetch("https://api.indexnow.org/indexnow", {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=utf-8" },
      body: JSON.stringify(body),
    });

    return {
      ok: res.status === 200 || res.status === 202,
      status: res.status,
      submitted: validUrls.length,
      message: res.status >= 400 ? await res.text() : undefined,
    };
  } catch (err) {
    return {
      ok: false,
      status: 0,
      submitted: 0,
      message: err instanceof Error ? err.message : "Network error",
    };
  }
}
