"""
Insert content-grounded FAQ arrays into all 23 remaining procedure detail pages.

Each FAQ set is written specifically against the section bullets, body paragraphs,
and stats in the target page — not a generic template. Anchor for insertion is
`related={category.items}`, which appears once per page in a consistent location.
"""
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

# Map: relative page path -> list of (question, answer) tuples
FAQS = {
    # ========== CLEANINGS & PREVENTION ==========
    "app/procedures/cleanings-prevention/dental-exams-cleanings/page.tsx": [
        ("How often should I get a dental cleaning?",
         "We recommend a professional cleaning every 6 months for most adults. Patients with a history of gum disease, heavy tartar buildup, smokers, or those with certain medical conditions may need cleanings every 3–4 months. Dr. Martenson or your hygienist will recommend the right cadence at your first visit."),
        ("What's the difference between a cleaning and an exam?",
         "Every routine visit includes both. The exam is done by your dentist and covers oral cancer screening, gum disease evaluation, decay detection on every tooth surface, and a check of your existing fillings and crowns. The cleaning is performed by our registered dental hygienist and removes plaque and tartar above and below the gumline, followed by polishing."),
        ("What's the difference between plaque and tartar?",
         "Plaque is a soft, sticky film of bacteria, food debris, and saliva that builds up on teeth daily — you can disrupt it with brushing and flossing. Tartar (calculus) is plaque that has hardened onto the tooth surface; it forms above and below the gumline and can only be removed with the specialized instruments your hygienist uses."),
        ("Does the oral cancer screening hurt?",
         "Not at all — it's a visual and tactile exam that takes about 60 seconds. Your dentist looks and gently feels around your face, neck, lips, tongue, throat, and inside of your cheeks for any unusual lumps, color changes, or sores. Early detection dramatically improves outcomes for oral cancers, which is why we do it at every six-month visit."),
        ("Will the cleaning hurt if I have sensitive teeth?",
         "Most patients find routine cleanings comfortable, even with mild sensitivity. If you have heavy tartar buildup or gum inflammation, we may apply topical numbing gel. For patients with significant sensitivity or who haven't had a cleaning in a while, we can break the work into two visits or use local anesthesia — just let us know."),
        ("How long does a typical cleaning appointment take?",
         "Plan for about 45–60 minutes for an established patient — that covers the hygienist's cleaning, polishing, the dentist's exam, and any necessary X-rays. New-patient visits run longer (60–90 minutes) because we'll do a full set of baseline X-rays and a comprehensive periodontal evaluation."),
        ("Should I brush and floss right before my appointment?",
         "Yes — brush and floss normally that day. It doesn't change what we'll do, but it makes the cleaning more comfortable for you and lets your hygienist focus on the areas you can't reach at home. There's no need to do anything special or extra."),
        ("What if I haven't been to the dentist in years?",
         "You're not alone, and we won't lecture you. At your first visit we'll do a thorough exam and decide together whether a regular cleaning is appropriate or whether a deeper periodontal cleaning is needed first. We see patients all the time who have been away from the dentist for 5, 10, or even 20 years — the only wrong move is continuing to wait."),
    ],
    "app/procedures/cleanings-prevention/dental-x-rays/page.tsx": [
        ("Are dental X-rays safe during pregnancy?",
         "Routine dental X-rays are generally postponed during pregnancy unless there's an urgent diagnostic need (severe pain, infection, trauma). If an X-ray is necessary, we use a lead apron with a thyroid collar and modern low-dose digital sensors. Always tell us if you're pregnant or trying to conceive so we can plan accordingly."),
        ("How much radiation am I exposed to during dental X-rays?",
         "A full-mouth series of dental X-rays delivers about the same radiation you'd receive from one day of natural background exposure (sun, air, rocks, food). Single bite-wing X-rays at a recall visit are roughly a fraction of that. We use lead aprons, thyroid collars, and modern fast-film/digital sensors to keep exposure as low as possible."),
        ("How often should I have dental X-rays taken?",
         "Bite-wing X-rays — the small ones taken with you biting down on a tab — are recommended once or twice a year at your recall visits to catch new decay between teeth. A full-mouth series is taken on new patients and then every 3–5 years. Your dentist will adjust based on your dental history, age, and risk for disease."),
        ("What's the difference between bite-wing X-rays and a full-mouth series?",
         "Bite-wing X-rays show the crowns of your upper and lower back teeth biting together — they're the best tool for spotting decay between teeth and checking bone level. A full-mouth series captures every tooth from crown to root tip across multiple individual films. The full series is used as a baseline for new patients and to check for problems beneath the gumline."),
        ("Why do I need X-rays if I'm not having pain?",
         "Most dental problems are silent in their early stages — decay between teeth, small abscesses, bone loss, cysts, and even tumors typically don't cause pain until they're advanced. X-rays catch these issues when they're still small and inexpensive to fix. Waiting for pain usually means a bigger problem and a bigger procedure."),
        ("Can I refuse dental X-rays?",
         "You can decline X-rays, but we're then diagnosing partially blind — about a third of dental problems aren't visible during a clinical exam alone. We'll always explain why we're recommending a specific X-ray and how often. If you'd like to push out the cadence, talk to your dentist about your concerns."),
        ("Do children need dental X-rays?",
         "Yes — children typically get X-rays once a year, more frequently if they have a high cavity risk or are in mixed-dentition (losing baby teeth, gaining permanent ones). X-rays in kids monitor tooth development, look for decay between teeth, and check that adult teeth are coming in correctly."),
        ("Are digital X-rays safer than film X-rays?",
         "Yes — digital X-ray sensors deliver about 70–80% less radiation than traditional film. We use digital imaging throughout the practice, which also means we can review your images chairside on a screen and store them as part of your record without any chemical processing."),
    ],
    "app/procedures/cleanings-prevention/fluoride-treatment/page.tsx": [
        ("Is fluoride safe for children?",
         "Yes — fluoride is safe and recommended for children in the doses used in toothpaste, professional treatments, and most municipal water. The key is amount: too much fluoride during tooth development (under age 8) can cause fluorosis, mild white spots on developing teeth. We coach parents on how much toothpaste to use at each age and whether supplements are appropriate."),
        ("What is fluorosis?",
         "Fluorosis is cosmetic — white spots, streaks, or in severe cases brown discoloration on teeth — caused by ingesting too much fluoride while teeth are still developing under the gums (under age 8). It's preventable by using the right amount of toothpaste for your child's age and by checking whether your home water source already contains fluoride before considering supplements."),
        ("Do adults need fluoride treatments?",
         "Many do. Adults with exposed root surfaces from gum recession, frequent cavities, dry mouth from medications, or who don't drink fluoridated tap water benefit from professional fluoride. It's typically a quick varnish application at the end of your cleaning visit — no extra time required."),
        ("What's the difference between topical and systemic fluoride?",
         "Topical fluoride sits on the outside of erupted teeth, strengthening enamel from the surface — it's what you get from toothpaste, mouth rinses, and our in-office varnish. Systemic fluoride is ingested (water, drops, tablets) and incorporates into developing teeth before they erupt. Both work; topical is the main protection for adults."),
        ("Why does my child need a professional fluoride treatment at every cleaning?",
         "Twice-yearly professional fluoride applications give kids a concentrated dose that toothpaste alone can't provide, especially around the deep pits and fissures of new molars where most childhood cavities form. The treatment takes 1–2 minutes and is a leading reason childhood cavity rates have dropped over the last 50 years."),
        ("Will fluoride alone prevent cavities?",
         "No — fluoride supports good habits, it doesn't replace them. To prevent cavities you still need to brush twice a day, floss daily, eat balanced meals, limit sugar between meals, and see your dentist regularly. Fluoride makes enamel more resistant to acid attack, but it can't undo a poor home-care routine."),
        ("What does a professional fluoride treatment feel like?",
         "It feels like having a thin varnish painted onto your teeth with a tiny brush — takes about 30 seconds, then dries quickly. We ask you to avoid eating hard or sticky foods for 4 hours afterward so the fluoride can do its work on the enamel."),
        ("When are fluoride supplements (drops or tablets) recommended?",
         "Only if your child isn't getting enough fluoride from their water supply and is at higher-than-average cavity risk. Drops are for infants; tablets for children through the teen years. We never recommend supplements without first checking your home water source — too much fluoride during tooth development causes fluorosis."),
    ],
    "app/procedures/cleanings-prevention/home-care/page.tsx": [
        ("How long should I brush my teeth each time?",
         "Two minutes, twice a day — the ADA's standard recommendation. Most adults brush for 30–45 seconds without realizing it. If you have an electric toothbrush, most models have a built-in 2-minute timer with 30-second quadrant pulses. Otherwise, hum a song or set a phone timer."),
        ("Are electric toothbrushes better than manual?",
         "For most adults, yes — particularly oscillating/rotating heads. Electric brushes remove more plaque with less effort, and the built-in timer keeps you brushing for the right duration. They're especially helpful for patients with arthritis, dexterity issues, braces, or a history of gum disease. A good manual brush used correctly can still do an excellent job — technique matters more than the tool."),
        ("Should I rinse with mouthwash every day?",
         "Not necessarily. Mouthwash can supplement brushing and flossing but doesn't replace either. If you use one, choose ADA-approved varieties and ask us whether antibacterial, fluoride, or alcohol-free is right for your specific situation. Patients with dry mouth, gum disease, or frequent cavities benefit most from a daily medicated rinse."),
        ("What's the right way to floss?",
         "Take about 12–16 inches of floss, wrap most of it around your middle fingers leaving about 2 inches between hands. Use your thumbs and forefingers to guide the floss between teeth with a gentle sawing motion. Curve the floss into a 'C' shape around each tooth and slide it gently beneath the gumline. Move up and down — don't snap it down."),
        ("How often should I replace my toothbrush?",
         "Every 3 months — or sooner if the bristles are bent, splayed, or matted. Worn bristles don't clean effectively and can irritate gums. Also replace your brush after you've had a cold, flu, or strep throat to avoid re-exposing yourself to lingering bacteria."),
        ("Is it OK to brush right after eating?",
         "Wait about 30 minutes after acidic foods or drinks (citrus, soda, wine, coffee). Acid temporarily softens enamel, and brushing immediately can scrub off the softened surface. Rinsing with water right after eating is fine and helps neutralize acid. Otherwise, brushing twice a day at consistent times is what matters most."),
        ("Do I need to floss if I brush twice a day?",
         "Yes — flossing reaches the surfaces between teeth where your toothbrush physically can't go. That space is where most cavities between teeth and where most periodontal pockets begin. Brushing alone leaves about 35% of your tooth surface uncleaned. Daily flossing covers that gap."),
        ("What's the best way to clean my tongue?",
         "Brush your tongue from back to front with your regular toothbrush, or use a dedicated tongue scraper. The back of the tongue harbors most of the bacteria that cause bad breath. A few gentle strokes is enough — don't scrub hard."),
    ],
    "app/procedures/cleanings-prevention/how-to-properly-brush-floss/page.tsx": [
        ("What does proper brushing technique actually look like?",
         "Hold the brush at a 45-degree angle to where your gums meet your teeth. Use small, gentle, circular motions — not back-and-forth scrubbing. Cover every surface of every tooth (outside, inside, chewing surface). Pay extra attention to the back molars and the inside of your front teeth, which most people miss. Two minutes total, twice a day."),
        ("Is harder pressure better when brushing?",
         "No — and it's actively harmful. Hard pressure with a stiff brush wears down enamel and pushes gums into recession. Use a soft-bristled brush and gentle pressure: if the bristles are splayed flat, you're pushing too hard. Electric toothbrushes do the work for you — you only need to guide them along the gumline."),
        ("Why does my floss bleed when I use it?",
         "Bleeding gums almost always mean inflammation from plaque sitting along or under the gumline — this is gingivitis, the earliest stage of gum disease. Counterintuitively, the solution is to floss more, not less. With consistent daily flossing for 1–2 weeks, healthy gums stop bleeding. If bleeding persists after two weeks, schedule a visit."),
        ("Can I use a water flosser instead of regular floss?",
         "Water flossers are an excellent supplement and especially helpful around braces, bridges, implants, and tight contacts. For most patients we recommend both — string floss to mechanically disrupt plaque between teeth, water flosser to flush debris from under the gumline. If string floss is impossible for you, a water flosser used daily is much better than nothing."),
        ("Should I brush before or after breakfast?",
         "Either works — the key is consistency. Brushing before breakfast removes the overnight bacterial buildup and lays down a layer of fluoride before you eat. Brushing after breakfast cleans away food debris. If you eat something acidic (citrus juice, coffee, etc.), wait 30 minutes before brushing to avoid scrubbing softened enamel."),
        ("How can I tell if my toothbrush is too hard?",
         "Look at the bristles after a few weeks of use — if they're splayed outward, matted, or bent over, the brush is wearing out (or you're pressing too hard). The ADA recommends 'soft' or 'extra-soft' for almost everyone. Medium and hard brushes do more damage than they help."),
        ("Can I brush too much?",
         "Yes — brushing more than 3 times a day, or brushing too hard, can wear down enamel and cause gum recession. The goal is twice-daily thorough brushing, not constant scrubbing. If you feel the urge to brush after every meal, rinsing with water is a better alternative."),
        ("Why is the chewing surface of back teeth harder to keep clean?",
         "Molars have deep grooves (pits and fissures) on their chewing surface — narrow valleys where toothbrush bristles physically can't reach. That's why most cavities in kids form on chewing surfaces, and why we sometimes recommend dental sealants for those grooves. For adults, technique matters: angle the brush directly into the chewing surface and use back-and-forth strokes there."),
    ],
    "app/procedures/cleanings-prevention/panoramic-x-rays/page.tsx": [
        ("What's the difference between a panoramic X-ray and a regular dental X-ray?",
         "A regular bite-wing or periapical X-ray is taken with a small sensor inside your mouth and shows a few teeth in detail. A panoramic X-ray is taken from outside the mouth by a machine that rotates around your head — it captures all upper and lower teeth, both jaws, sinuses, and TMJ joints in a single wraparound image. Less detail per tooth, much broader view."),
        ("When is a panoramic X-ray needed?",
         "Most often for wisdom-teeth evaluation, dental implant planning, suspected sinus problems causing tooth pain, jaw fractures, TMJ assessment, and orthodontic planning. It's also helpful for patients with severe gag reflexes who can't tolerate intraoral sensors. Most patients don't need a panoramic X-ray at every visit — it's done on an as-needed basis."),
        ("Do I have to bite down on anything for a panoramic X-ray?",
         "Just a small plastic bite tab to hold your front teeth in the right position. You stand still while the machine rotates around your head — typically 15–20 seconds. The plastic positioning piece can feel a little awkward, but the X-ray itself is fast and painless."),
        ("How long does a panoramic X-ray take?",
         "About 5 minutes total — most of it positioning. The scan itself is 15–20 seconds while the rotating arm moves around your head. The image appears on the screen immediately for the dentist to review."),
        ("Is a panoramic X-ray safer than other X-rays?",
         "Per image, yes — panoramic X-rays deliver less radiation than a full-mouth series of intraoral X-rays because they capture everything in a single exposure rather than 14–20 individual films. They also avoid film placement in the mouth, which is helpful for patients with strong gag reflexes."),
        ("Will a panoramic X-ray show cavities?",
         "Small cavities between teeth — no, not reliably. The image isn't sharp enough at the tooth level. For that, we rely on bite-wing X-rays. Panoramic X-rays show structural problems: impacted teeth, jaw fractures, large cysts, bone loss, sinus involvement, and developmental abnormalities."),
        ("Why does the dentist need a panoramic X-ray to plan implants?",
         "To check the position of the mandibular nerve (the major nerve running through your lower jaw) and the floor of the sinus (in the upper jaw). Implants must be placed without contacting either. The panoramic image — sometimes combined with a 3D cone-beam scan — maps out the safe placement zone."),
        ("Can a panoramic X-ray detect TMJ problems?",
         "It can show the bony structures of the TMJ joints and any obvious fractures or arthritis. For soft-tissue diagnosis of the disc or muscle problems, MRI is more useful. Panoramic imaging is often the first imaging step when TMJ pain is suspected."),
    ],
    # ========== COSMETIC DENTISTRY ==========
    "app/procedures/cosmetic-dentistry/cerec/page.tsx": [
        ("What does CEREC stand for?",
         "Chairside Economical Restoration of Esthetic Ceramic — a digital system that designs and mills custom ceramic crowns, onlays, inlays, and veneers right in our office. The 'chairside' part is the key benefit: no temporary crowns, no second visit, no lab wait."),
        ("How long does a CEREC crown procedure take?",
         "About 1.5–2 hours total in a single visit. Roughly 30 minutes to prepare the tooth and take the 3D scan, 15 minutes for Dr. Martenson to design the restoration on screen, 15 minutes for the milling machine to carve it from a ceramic block, then 30 minutes to fit, polish, and bond it. You walk out with the permanent restoration in place."),
        ("Is a CEREC crown as durable as a traditional lab-made crown?",
         "Yes — modern CEREC ceramic blocks are made from the same high-strength materials (lithium disilicate or zirconia) used by dental labs. Recent studies show 10+ year survival rates comparable to traditional lab crowns. The main difference is speed of delivery, not durability."),
        ("Do I need a temporary crown with CEREC?",
         "No — that's one of the biggest advantages. Traditional crowns require a temporary while the lab fabricates the permanent (2–3 weeks). CEREC eliminates that step. You leave the appointment with the final, permanent crown bonded in place."),
        ("How long do CEREC restorations last?",
         "Studies show most CEREC restorations last 10+ years with good care. Like any porcelain restoration, longevity depends on your bite, grinding habits, and oral hygiene. Patients who clench or grind heavily may need a nightguard to protect the investment."),
        ("Is CEREC more expensive than a traditional crown?",
         "Pricing is comparable to traditional lab crowns at most practices — and CEREC often saves on the lab fee and second-visit time. You'll get an exact quote at your consultation. Coverage by dental insurance is identical to a traditional crown."),
        ("Can CEREC make veneers?",
         "Yes — CEREC can mill porcelain veneers in a single visit, though most patients who want a multi-veneer smile makeover still prefer lab-fabricated veneers for the highest aesthetic refinement. CEREC veneers are ideal for single-tooth replacements or smaller cases."),
        ("Who isn't a candidate for CEREC?",
         "Patients with a history of breaking ceramic restorations or a very deep bite that puts unusual force on the front teeth may not be ideal candidates. Severe grinders (bruxism) need a nightguard regardless of whether the restoration is CEREC or lab-made. Dr. Martenson will evaluate during your consultation."),
        ("Does CEREC use natural-looking materials?",
         "Yes — CEREC ceramic blocks come in a full range of tooth shades and translucencies. We choose a block matched to your existing teeth and then characterize it (glaze, staining) before bonding. Most patients can't tell their CEREC crown from their natural teeth."),
    ],
    "app/procedures/cosmetic-dentistry/invisalign/page.tsx": [
        ("How much does Invisalign cost in Piedmont, CA?",
         "Most cases at our practice range from $4,500–$7,500 depending on complexity (how many trays, total treatment length, and whether refinements are needed). We provide a complete written quote after your consultation and iTero scan. CareCredit and Sunbit financing are available."),
        ("Can I eat with my Invisalign aligners in?",
         "No — you remove the aligners for every meal, snack, and any drink other than water. This is actually one of Invisalign's biggest advantages over traditional braces: no food restrictions, no broken brackets from popcorn or bagels. You just brush before putting them back in."),
        ("How long does Invisalign treatment take?",
         "Most adult cases run 6–18 months depending on the severity of misalignment. Simple cases (minor crowding, small gaps) can finish in 6–9 months. Moderate cases (crossbites, deeper crowding) typically run 12–18 months. Dr. Martenson will give you a specific timeline after the iTero scan."),
        ("Will Invisalign work for severe cases?",
         "Invisalign handles mild to moderate orthodontic concerns extremely well — crooked teeth, crowding, gaps, mild overbites/underbites/crossbites. For severely rotated teeth, large skeletal jaw discrepancies, or cases that require surgical correction, traditional braces or referral to an orthodontist may be more appropriate. We'll be honest about whether Invisalign is the right tool for your case."),
        ("Are there age restrictions for Invisalign?",
         "Invisalign is recommended for adults 18+ in our practice — the 22-hour daily wear requirement is the make-or-break factor, and adults are typically more reliable about compliance. Teen versions exist but require strong family support. The aligners work mechanically the same at any age."),
        ("Does Invisalign hurt?",
         "Mild pressure and soreness when you switch to a new aligner — usually fades within 24–48 hours. Because the trays are smooth plastic, you don't get the cheek and lip irritation that traditional metal braces cause. Most patients describe the discomfort as much milder than they expected."),
        ("How do I clean my Invisalign aligners?",
         "Rinse them with room-temperature water every time you take them out. Brush them gently with a soft-bristled toothbrush and clear soap (not toothpaste — it can scratch). Don't use hot water or run them through the dishwasher — heat warps the plastic. Invisalign sells official cleaning crystals as an optional weekly soak."),
        ("What happens if I lose an aligner?",
         "Tell us right away — usually we can either advance you to the next aligner (if you've worn the current one long enough) or order a replacement from Invisalign. Don't go without an aligner for more than 24 hours; your teeth will start to shift back and you may need to backtrack a tray."),
        ("Will I need a retainer after Invisalign?",
         "Yes — for life, just like with traditional braces. Teeth naturally try to drift back toward their original positions after any orthodontic treatment. We make clear Vivera retainers at the end of your case; most patients wear them nightly indefinitely. Skipping the retainer is the #1 reason teeth relapse."),
    ],
    "app/procedures/cosmetic-dentistry/porcelain-veneers/page.tsx": [
        ("How much do porcelain veneers cost per tooth?",
         "In our area, porcelain veneers typically run $1,500–$2,500 per tooth depending on the case complexity, lab used, and how much shape design is involved. A full smile makeover (6–10 upper veneers) is a significant investment but lasts 15+ years with care. You'll get an exact written quote at your consultation."),
        ("How many veneers do most patients get?",
         "It depends on what shows when you smile. Some patients want a single veneer to fix one chipped or stained tooth. Most cosmetic cases use 6–8 upper veneers (front teeth and the teeth visible at the corners of your smile). Full smile designs may include 10 upper + 8 lower. We'll plan together based on what you see in the mirror."),
        ("Do veneers ruin your natural teeth?",
         "We remove a very thin layer of enamel — typically 0.3–0.5mm — to make room for the porcelain. This preparation is permanent (the tooth will always need a veneer or crown going forward), but it's much more conservative than a full crown. Some 'no-prep' veneer cases are possible for naturally small or worn teeth."),
        ("How long do porcelain veneers last?",
         "Many years — typically 15–20+ with good care. Like any dental restoration, they're not permanent and may eventually need replacement. Avoiding habits that crack veneers (biting fingernails, opening packaging with teeth, ice chewing) and wearing a nightguard if you grind extends their life significantly."),
        ("Will my veneers look fake?",
         "Not when done well — that's the whole point of custom porcelain. We choose the color, shape, and translucency to match your face and existing teeth. The most common cosmetic mistake is veneers that are too white or too uniform — we work with you to find the right look, not a magazine cover."),
        ("Can veneers be whitened?",
         "No — porcelain doesn't respond to bleaching. If you want a whiter smile, we whiten your natural teeth first, then match your veneers to the new shade. Plan any whitening before veneer placement; you can't darken or lighten veneers later without replacing them."),
        ("What's the difference between veneers and crowns?",
         "A veneer covers only the front and biting edge of a tooth — like a thin shell bonded to the visible surface. A crown encases the entire tooth, all the way around. Veneers are for cosmetic improvement of front teeth that are mostly healthy. Crowns are used when the tooth is structurally damaged, decayed, or has had a root canal."),
        ("Can veneers fix crooked teeth?",
         "For mildly crooked or rotated front teeth, yes — veneers can give the appearance of a straight smile. For more significant misalignment, Invisalign or traditional orthodontics first, then veneers if needed, gives a more conservative result. Dr. Martenson can help you decide which path makes sense."),
        ("How are veneers different from composite bonding?",
         "Composite bonding uses tooth-colored filling material applied directly to the tooth and shaped chairside — cheaper, single visit, and reversible, but stains over time and lasts 5–7 years. Porcelain veneers are custom-made in a lab, more expensive, and require 2 visits — but they don't stain and last 15+ years. Bonding is great for small fixes; veneers are the long-term answer."),
    ],
    "app/procedures/cosmetic-dentistry/surgery/page.tsx": [
        ("What is a 'gummy smile'?",
         "A gummy smile is when more than about 2mm of gum tissue shows above your upper teeth when you smile widely. The teeth themselves can look short or square. Causes include excess gum tissue covering the teeth (most common), shorter-than-average teeth, or an over-active upper lip. Surgical crown lengthening addresses the gum-tissue cause."),
        ("Will the surgery hurt?",
         "The procedure itself is done with local anesthesia and is comfortable — most patients say it's similar to a deep cleaning. Many opt for nitrous oxide for added relaxation. After the anesthetic wears off, mild soreness for 2–3 days is typical and managed with over-the-counter pain relief."),
        ("How long is the recovery from crown lengthening?",
         "Most patients return to normal activities the next day. Mild swelling and tenderness for 3–5 days is typical. Full gum healing takes 2–3 months — during that time the gumline gradually settles into its final position. If we're pairing with veneers, those are typically placed about 8–12 weeks after the surgery."),
        ("Why is crown lengthening often paired with veneers?",
         "The two procedures complement each other: crown lengthening exposes more tooth structure (so you have more 'canvas'), and veneers refine the shape and color of that newly exposed tooth. Doing one without the other can leave a result that's either too short (gummy smile + veneers alone) or unbalanced (longer teeth that still look stained or chipped). Together they produce a balanced smile design."),
        ("Will my gums grow back to where they were?",
         "When done properly, no — the procedure reshapes both gum tissue and a small amount of underlying bone, which establishes a stable new gumline. The 2–3 months of healing is your tissue settling into its permanent position. Gums don't 'creep back' unless there's an underlying issue."),
        ("Is crown lengthening covered by insurance?",
         "Cosmetic crown lengthening (to fix a gummy smile) is typically not covered by dental insurance. Functional crown lengthening (to expose more tooth so a new crown can be placed safely) is often covered. We'll verify your benefits ahead of time and let you know your out-of-pocket cost."),
        ("Can crown lengthening fix uneven gumlines?",
         "Yes — that's one of its most common uses. We can reshape the gumline of a single tooth or recontour across multiple teeth to create a symmetrical, balanced smile line. This is often combined with veneers for the most polished final result."),
        ("How is surgical crown lengthening different from simple gum contouring?",
         "Gum contouring (sometimes called gum reshaping with a laser) removes only soft tissue and is reversible — gums can re-cover the tooth over time. Surgical crown lengthening reshapes both gum tissue and a small amount of bone, which makes the change permanent. The right procedure depends on how much exposure you need and how the tooth meets the bone."),
    ],
    "app/procedures/cosmetic-dentistry/tooth-whitening/page.tsx": [
        ("How much does professional teeth whitening cost?",
         "Custom take-home tray whitening at our practice typically runs $400–$600 — that covers the molds, custom trays, and several syringes of professional-strength gel. In-office whitening (single appointment, faster results) runs higher. Both are significantly less than the cumulative cost of repeatedly buying over-the-counter strips that don't deliver lasting results."),
        ("Will whitening work on my crowns and fillings?",
         "No — whitening only works on natural tooth enamel. Crowns, veneers, and tooth-colored fillings won't change color. If you have visible restorations and want to whiten, we whiten the natural teeth first and then replace any restorations afterward to match the new lighter shade. We'll plan this with you at your consultation."),
        ("Is professional whitening better than over-the-counter products?",
         "Significantly. Professional gels contain higher concentrations of bleaching agents (calibrated to your enamel by your dentist), and the custom trays keep the gel in contact with your teeth — not your gums. Most over-the-counter strips deliver 6–10% peroxide; professional gels are 15–35%. Results last longer and look more uniform."),
        ("How long do whitening results last?",
         "Typically 1–3 years before a touch-up is needed. The biggest factors are coffee, tea, red wine, smoking, and how diligent you are with your home-care routine. We provide extra gel syringes so you can do a 2–3 night touch-up at home whenever you notice your shade starting to drift."),
        ("Will whitening hurt my teeth?",
         "Temporary sensitivity to cold air or cold liquids is common during the 2-week active whitening period — it stops within a few days of finishing. We can prescribe a desensitizing gel if it bothers you. Whitening at the concentrations we use doesn't damage enamel; the sensitivity comes from the bleaching agent passing through dentin to the nerve, which calms down once you stop."),
        ("How white can my teeth actually get?",
         "Most patients see 3–8 shades of improvement on the standard dental shade guide. Your starting color, the cause of staining (genetic, food/drink, age, medication), and the porosity of your enamel all factor in. Tetracycline staining from childhood antibiotics is the hardest to budge; food and age-related yellowing responds best."),
        ("Can pregnant or nursing women whiten their teeth?",
         "We recommend postponing whitening during pregnancy and breastfeeding — not because of proven harm, but because peroxide hasn't been formally studied in those populations, and we'd rather err on the side of caution. Routine cleanings are still completely safe."),
        ("Why do I need to whiten before getting new dental work?",
         "Because crowns, veneers, and fillings can't be whitened later — once they're placed, they're locked in that shade. If you want a whiter smile and need new restorations, the sequence is: whiten first, wait two weeks for the color to stabilize, then place restorations matched to your new shade. Reversing this order means redoing the restoration to match."),
        ("What causes tooth discoloration in the first place?",
         "Surface staining from coffee, tea, red wine, tobacco, and certain foods (dark berries, soy sauce, curry). Internal discoloration from age (enamel thins, revealing the yellower dentin underneath), genetics, medication (especially tetracycline taken in childhood), and trauma. Surface stains respond to whitening; deep internal discoloration may need veneers."),
    ],
    # ========== PERIODONTAL SERVICES ==========
    "app/procedures/periodontal-services/bone-grafting/page.tsx": [
        ("Why do I need a bone graft for a dental implant?",
         "Implants need to be anchored in healthy, dense jawbone. If you've been missing a tooth for a while, the bone in that area has likely shrunk — your jaw loses bone density without a tooth root to stimulate it. A bone graft rebuilds enough volume and density for the implant to integrate securely. Without sufficient bone, an implant can fail."),
        ("Where does the bone for a graft come from?",
         "Three main sources: your own body (autogenous — usually from the chin, jaw, hip, or shin); a tissue bank (allograft — donated, processed human bone); or animal source (xenograft — typically bovine bone, processed to be inert). For most cases at our practice, an allograft or xenograft works well and avoids a second surgical site."),
        ("Is bone grafting painful?",
         "The procedure itself is done under local anesthesia and is generally comfortable. Postoperative soreness for 3–5 days is typical and well-managed with over-the-counter pain relief. If we're harvesting from a second site (your own bone), there's some additional discomfort at the donor site — most patients describe it as similar to a bruise."),
        ("How long does a bone graft take to heal?",
         "The initial soft-tissue healing happens in 2 weeks, but the graft itself integrates into your jawbone over 3–6 months. Implants typically can't be placed until integration is complete and confirmed by X-ray. We'll see you at 10 days, then again at 3 months and 6 months to monitor progress."),
        ("Are cow-derived (xenograft) bone grafts safe?",
         "Yes — xenograft material is processed to remove all organic components, leaving only the mineral scaffolding. It's been used safely for decades and is one of the most common materials worldwide. There's no risk of disease transmission because the biological material is destroyed during processing."),
        ("What is a sinus lift, and is it the same as bone grafting?",
         "A sinus lift is a specific type of bone grafting done in the upper jaw (premolar/molar region). When implants are planned in that area but the sinus floor is too close, we gently lift the sinus membrane and pack bone graft material beneath it. After healing, there's enough bone for safe implant placement. It's covered in detail on our sinus augmentation page."),
        ("Will my body reject a bone graft?",
         "Bone grafts don't 'reject' the way an organ transplant might — the materials we use are inert mineral scaffolds, not living tissue. The graft fails only if it doesn't integrate properly (uncommon when placed by an experienced periodontist), if infection occurs, or if mechanical stress disturbs the site during healing."),
        ("What happens if I skip the bone graft?",
         "If the implant site doesn't have enough bone, we have a few options: place a smaller-diameter or shorter implant (sometimes possible), use a different replacement option like a bridge or denture, or simply leave the gap. Forcing an implant into insufficient bone leads to early failure, so a graft is usually the right investment."),
    ],
    "app/procedures/periodontal-services/crown-lengthening/page.tsx": [
        ("What's the difference between crown lengthening and gum contouring?",
         "Gum contouring (or gum reshaping with a laser) removes only soft tissue and is reversible — gums can grow back over time. Crown lengthening reshapes both gum tissue and a small amount of underlying bone, which makes the change permanent. Contouring is for minor cosmetic adjustments; crown lengthening is needed when more substantial repositioning is required or when prepping for a crown."),
        ("How long does it take for the gums to heal after crown lengthening?",
         "Initial soft-tissue healing happens in 10–14 days. Full healing — when the gumline has settled into its final position — takes 2–3 months. If we're planning veneers or new crowns on the treated teeth, we wait until full healing before placement so the final result matches the stable gumline."),
        ("Is crown lengthening painful?",
         "The procedure is done with local anesthesia and is comfortable during. Postoperative soreness for 3–5 days is typical, well-managed with over-the-counter pain relief. The surgical site is protected with a periodontal bandage for the first week."),
        ("Why is crown lengthening needed before a crown?",
         "A crown needs adequate tooth structure above the gumline to bond properly. If a tooth has broken near or below the gumline (from decay, fracture, or large old fillings), there's not enough exposed tooth for the crown to grip. Crown lengthening exposes the additional tooth needed, giving the new crown a stable, healthy foundation."),
        ("Will my teeth look longer permanently after crown lengthening?",
         "Yes — that's the point. The newly exposed tooth surface is what gives you a balanced smile (cosmetic case) or a viable surface for a crown (restorative case). The gumline doesn't 'grow back' once both tissue and bone have been reshaped."),
        ("Can crown lengthening fix a single tooth or do you do all of them?",
         "Both. For a single tooth needing a crown, we'll often shape just that area — though we may also touch up the neighboring 1–2 teeth so the gumline transitions smoothly. For a gummy smile correction, we'll work across the visible front teeth (usually 6–8) so the result is symmetrical."),
        ("How is this different from cosmetic gum surgery on your cosmetic dentistry page?",
         "They're the same procedure, just listed in two contexts. The cosmetic dentistry page focuses on aesthetic gummy-smile correction; this periodontal page covers the full scope including restorative (prep-for-crown) and disease-related uses. The surgical technique is identical."),
        ("Will insurance cover crown lengthening?",
         "If the procedure is functional (necessary to place a crown, or to treat damaged teeth), insurance typically covers a significant portion. If it's purely cosmetic (gummy smile correction without restorative need), most plans treat it as elective and don't cover. We verify your benefits before booking and give you a clear cost estimate."),
    ],
    "app/procedures/periodontal-services/gum-grafting/page.tsx": [
        ("What causes gum recession in the first place?",
         "The two most common causes are periodontal disease (chronic gum infection breaking down tissue) and overly aggressive brushing with a hard-bristled brush. Other contributors include trauma, grinding or clenching (which puts unusual pressure on certain teeth), naturally thin tissue, and orthodontic movement. Identifying the cause is part of the treatment so it doesn't keep recurring."),
        ("Is a gum graft painful?",
         "The procedure itself is done under local anesthesia and is comfortable during. Most discomfort comes from the donor site (your palate) if a free or connective tissue graft was used — feels like a pizza burn for about a week. If we use an allograft (donated tissue), there's no second site and discomfort is much milder. Most patients return to work the next day."),
        ("How long does it take to heal after gum grafting?",
         "Initial soft-tissue healing is 2 weeks. The grafted tissue fully integrates over about 6 weeks, and the final aesthetic settling continues for several months. We'll see you at 1 week to remove the surgical dressing and again at 4 and 12 weeks to check on integration."),
        ("Where does the tissue come from for a gum graft?",
         "Three sources: your own palate (free gingival graft or connective tissue graft — most common, predictable healing), or processed donor tissue from a tissue bank (acellular dermal matrix allograft — no second site, slightly less predictable). Dr. Cangini will recommend the right approach for your case during consultation."),
        ("Can gums grow back without a graft?",
         "Unfortunately, no — receded gum tissue doesn't regenerate spontaneously. The goal of grafting is to add new tissue to the recession site so the root is covered. If recession is caught very early (just starting), sometimes addressing the cause (changing brushing technique, treating periodontal disease) can stop further loss — but rebuilding what's gone requires a graft."),
        ("Will my teeth still feel sensitive after grafting?",
         "Usually significantly less — that's one of the major benefits. The graft covers the exposed root (which is sensitive because it lacks the protective enamel of the crown). Most patients notice a dramatic reduction in cold and hot sensitivity within a few weeks of healing."),
        ("How long does a gum graft last?",
         "When done by a periodontist and properly cared for, a gum graft is permanent. The rare cases of graft 'failure' come from severe ongoing periodontal disease or continued aggressive brushing. We'll coach you on technique and home care to protect the result."),
        ("Will the grafted area look natural?",
         "Yes — modern grafting techniques produce excellent aesthetic results, especially when an experienced periodontist (Dr. Cangini in our practice) does the procedure. The grafted tissue blends with the surrounding gum tissue over the first few months. Patients are typically very happy with both the comfort relief and the appearance improvement."),
    ],
    "app/procedures/periodontal-services/maintenance/page.tsx": [
        ("How is periodontal maintenance different from a regular cleaning?",
         "A regular cleaning (dental prophylaxis) removes plaque and tartar from healthy teeth above the gumline. Periodontal maintenance is for patients who have already been treated for gum disease — it includes deeper cleaning below the gumline, careful checking of pocket depths, and ongoing monitoring to keep the disease from returning. Different procedure code, longer appointment, often more frequent."),
        ("Why do I need cleanings every 3 months instead of every 6?",
         "Because plaque starts hardening into tartar within just 24 hours, and patients with treated gum disease re-form periodontal pockets much faster than people who've never had it. The quarterly cadence keeps bacterial colonies from re-establishing in the pockets where disease started. Stretching to 6 months often allows the disease to recur."),
        ("Can I ever go back to regular 6-month cleanings?",
         "For most periodontal patients, the answer is no — once gum disease has been present, the risk of recurrence stays elevated for life. The 3-month cadence is the standard of care that keeps your case stable. Some patients with very mild disease history and excellent home care may stretch to every 4 months, but we'll make that call together at your visits."),
        ("What happens at a periodontal maintenance visit?",
         "Pocket-depth measurements at every tooth, an oral cancer screening, an exam of all existing dental work, X-rays as needed, deep cleaning above and below the gumline, polishing, and a discussion of your home care. Total time about 60–75 minutes."),
        ("Will my insurance cover quarterly maintenance?",
         "Most plans cover 2 visits per calendar year at the cleaning rate, then quarterly visits are billed at the periodontal maintenance rate (different code). Many plans cover periodontal maintenance up to 4× per year; some cap at 2 with the rest as out-of-pocket. We verify your specific benefits and discuss any cost upfront."),
        ("What happens if I skip a maintenance visit?",
         "Tartar starts re-accumulating below the gumline immediately. Skipping one visit usually means pockets get a little deeper, gums become more inflamed, and the next visit takes longer to bring you back to baseline. Skipping multiple visits often leads to disease progression — sometimes requiring scaling and root planing or surgery again."),
        ("How long will I need to do quarterly maintenance?",
         "Indefinitely — for life. Periodontal disease is managed, not cured. Quarterly visits keep it in remission the same way regular medication keeps a chronic medical condition stable. The investment is far cheaper than letting the disease recur and needing surgery again."),
        ("Do I still need to floss daily between maintenance visits?",
         "Absolutely — and possibly more carefully than someone who's never had gum disease. Daily flossing disrupts the bacterial colonies that drive recurrence. Many of our maintenance patients also use a water flosser, interdental brushes, or medicated rinses. We coach the right tools for your case."),
    ],
    "app/procedures/periodontal-services/periodontal-scaling-root-planing/page.tsx": [
        ("What's the difference between scaling and root planing?",
         "Scaling removes plaque, tartar, and toxins from the visible tooth surface and from below the gumline. Root planing smooths the rough surface of the tooth root itself, which removes bacterial pockets and makes it harder for bacteria to recolonize. They're typically done together as one combined procedure."),
        ("Is scaling and root planing painful?",
         "We use local anesthesia in most cases so the procedure itself is comfortable. Some patients with mild disease can tolerate it with just topical numbing. After the anesthetic wears off, mild soreness and gum tenderness for 24–48 hours is typical and well-managed with over-the-counter pain relief."),
        ("How long does a scaling and root planing appointment take?",
         "Most cases are split into 2 appointments (one half of the mouth at each), each lasting about 60–75 minutes. Spreading the work allows us to be thorough and gives one side of your mouth a break between visits. Severe cases may need 4 quarterly appointments."),
        ("Will I need antibiotics after the procedure?",
         "Often, yes — either oral antibiotics for a few days, antibiotic-soaked medicated chips placed directly in the pockets, or both. The goal is to wipe out the bacterial colonies that the mechanical cleaning disrupted. Whether you need them depends on the severity of your disease and your medical history."),
        ("How often do I need scaling and root planing?",
         "It's typically a one-time treatment for an active periodontal disease episode — done once to get the disease under control. Afterward, you transition to quarterly periodontal maintenance visits, which prevent recurrence. Some patients may need the deep cleaning repeated years later if disease flares back up."),
        ("What's a 'pocket' and why does the depth matter?",
         "A pocket is the space between your tooth and the gum cuff around it. Healthy pockets measure 1–3mm. Pockets deeper than 4mm trap bacteria that you can't reach with brushing or floss. The deeper the pocket, the worse the disease — at 5mm we get worried, at 7+mm we may need surgical intervention. We measure every pocket at your initial perio exam."),
        ("Does scaling and root planing reverse gum disease?",
         "It stops disease progression and shrinks inflamed gum tissue — pockets usually become 1–2mm shallower as gums tighten back around clean root surfaces. It doesn't regrow bone that's already been lost. With consistent quarterly maintenance, you can keep the disease in remission for life."),
        ("Will my teeth be more sensitive after the procedure?",
         "Possibly — your root surfaces have been cleaned of the bacterial film that was insulating them, and gums may shrink back slightly as inflammation resolves. Temporary cold sensitivity for a few weeks is common. We can prescribe a desensitizing toothpaste if it's bothering you. Most patients find the sensitivity resolves as roots build up natural protective layers."),
    ],
    "app/procedures/periodontal-services/sinus-augmentation/page.tsx": [
        ("Why do I need a sinus lift before getting an upper-jaw implant?",
         "When you lose an upper back tooth, the maxillary sinus (the air pocket above your upper jaw) gradually drops downward and the bone underneath shrinks. To place an implant safely, we need enough bone between the implant and the sinus floor. A sinus lift raises the sinus membrane and packs bone graft material beneath it, creating space for safe implant placement."),
        ("Is sinus augmentation surgery painful?",
         "The procedure is done with local anesthesia (sometimes IV sedation for larger cases) and is comfortable during. Postoperative discomfort for 5–7 days is typical — most patients describe it as similar to a sinus infection, well-managed with over-the-counter pain relief. Mild swelling and occasional minor nosebleed is normal in the first few days."),
        ("How long does it take to heal before I can get implants?",
         "Most cases require 4–9 months of healing before implant placement, depending on how much bone was needed and which technique was used. In some cases — when there's enough existing bone — the sinus lift and implant placement can be done simultaneously. Dr. Cangini will plan the timing during your evaluation."),
        ("Are there risks to having a sinus lift?",
         "Like any surgery, there are small risks: sinus membrane perforation (small tears usually heal on their own), infection (rare with proper antibiotic protocol), and graft failure (uncommon). Success rates with experienced periodontists like Dr. Cangini exceed 95%. Smoking significantly raises the risk of failure — we ask patients to stop smoking at least 2 weeks before and during healing."),
        ("Can the bone graft material come from a donor?",
         "Yes — we typically use allograft (processed human donor bone), xenograft (bovine), or synthetic bone substitute. All three are well-studied, safe, and avoid the need for a second surgical site to harvest your own bone. For very large defects, we may combine donor material with a small amount of your own bone for the best result."),
        ("Will I need to take antibiotics afterward?",
         "Yes — almost always. A short course of oral antibiotics (5–7 days) significantly reduces infection risk during the early healing period. We may also prescribe an antimicrobial mouth rinse. Take the full course exactly as prescribed even if you feel fine."),
        ("Are there any food or activity restrictions during healing?",
         "For the first 1–2 weeks: no nose blowing, no straws, no smoking, no swimming or strenuous exercise. Eat soft foods and avoid anything that creates pressure changes in the sinus (sneeze with mouth open, no flying if possible). Most patients return to normal activities within 7–10 days."),
        ("How successful is sinus augmentation?",
         "Very — implant success rates in sinus-augmented sites match those in native bone (95%+) when done by an experienced periodontist. The procedure has been done for over 40 years and is well-refined. The biggest predictors of success are no smoking, proper home care during healing, and following the timing recommendation for implant placement."),
    ],
    "app/procedures/periodontal-services/treatment/page.tsx": [
        ("How do you determine which periodontal treatment I need?",
         "We measure pocket depth at every tooth (1–3mm is healthy, 4mm is borderline, 5mm+ requires treatment), check for bleeding, look at recession, and review X-rays for bone loss. The combination tells us your disease stage — gingivitis (early, reversible), mild/moderate periodontitis, or advanced periodontitis. Treatment is matched to stage."),
        ("Can early gum disease be reversed?",
         "Yes — gingivitis (the earliest stage, with red/swollen gums but no bone loss yet) is fully reversible with 1–2 regular cleanings, improved home care, and possibly an antimicrobial rinse. Once disease progresses to periodontitis (bone loss has occurred), it can be stopped and managed but not fully reversed."),
        ("What does 'stage' mean in periodontal disease?",
         "Stages describe how advanced the disease is: Stage I is the mildest (1–2mm bone loss), Stage IV is the most severe (>5mm bone loss with potential tooth mobility). We also describe disease as gingivitis (just gum inflammation, no bone involvement) or periodontitis (bone loss has started). Treatment intensity scales with stage."),
        ("Why is scaling and root planing done one quadrant at a time?",
         "Two reasons: it lets us be thorough and not rush, and it gives you a 'good side' of the mouth to chew and rest with while the other heals. The split-mouth approach is the standard of care for moderate-to-advanced cases. Mild cases can sometimes be done in 1–2 visits."),
        ("When would I need a periodontist (specialist)?",
         "We refer to Dr. Cangini (our in-house board-certified periodontist) for surgical cases: pocket reduction surgery, bone regeneration, gum or bone grafting, and complex implant placement. Most early- and moderate-stage cases we treat in-house with the general dentist and hygienist."),
        ("How long does periodontal treatment take?",
         "Active treatment for moderate-to-severe disease is typically 4–8 weeks (2 deep-cleaning visits about 2 weeks apart, then a re-evaluation visit at 4–6 weeks). After active treatment, you move into the ongoing maintenance phase (quarterly visits) for life. The whole cycle gets the disease under control; maintenance keeps it controlled."),
        ("What's the success rate of non-surgical periodontal treatment?",
         "For mild-to-moderate periodontitis, scaling and root planing combined with consistent home care and quarterly maintenance has an 80%+ success rate at keeping disease stable long-term. Severe cases (deep pockets, significant bone loss) often require surgical care for the best outcome."),
        ("Will I need ongoing treatment for the rest of my life?",
         "Yes — periodontal disease is managed, not cured. Once you've had it, you'll need quarterly maintenance visits indefinitely to prevent recurrence. The good news: with consistent maintenance, the vast majority of patients keep their teeth for life. Skipping maintenance is what allows the disease to come back."),
    ],
    "app/procedures/periodontal-services/what-is-periodontal-gum-disease/page.tsx": [
        ("What are the earliest warning signs of gum disease?",
         "Bleeding when you brush or floss, redness or puffiness at the gumline, bad breath that doesn't go away with brushing, and gums that look like they're pulling away from teeth. Most people notice these signs and assume they're normal — they aren't. Catching gum disease at this stage (gingivitis) means it's fully reversible."),
        ("Why is gum disease called a 'silent' disease?",
         "Because it doesn't usually hurt until it's severe. Cavities cause toothache pretty quickly; gum disease can quietly destroy supporting bone for years with only subtle warning signs. The first time many patients notice anything wrong is when a tooth becomes loose — by then the disease has been progressing for a long time."),
        ("Can gum disease cause me to lose my teeth?",
         "Yes — periodontal disease is the #1 cause of tooth loss in adults in the developed world, ahead of cavities. The disease destroys the bone and ligament that hold teeth in place. Once enough support is lost, teeth become loose and eventually fall out or need extraction. Catching it early prevents that outcome."),
        ("Is gum disease linked to other health problems?",
         "Research has shown associations between chronic gum disease and heart disease, stroke, diabetes complications, lung infections (especially in older adults), and adverse pregnancy outcomes. The link is likely the inflammatory burden that chronic gum infection puts on the rest of the body. Treating gum disease is a quality-of-life and a general-health intervention."),
        ("Can gum disease be cured?",
         "Gingivitis (the earliest stage) — yes, fully reversible. Periodontitis (the bone-loss stage) — no, it can be stopped and managed but the bone that's been lost doesn't regrow on its own. Treatment + ongoing maintenance keeps the disease in remission for life. The earlier we catch it, the better the long-term outcome."),
        ("Is bleeding when I floss a sign of gum disease?",
         "Almost always, yes — bleeding gums indicate inflammation, which means bacterial plaque is sitting along or under the gumline. The fix is counterintuitive: floss more, not less. With consistent daily flossing for 1–2 weeks, healthy gums stop bleeding. If bleeding persists after 2 weeks of good home care, schedule an evaluation."),
        ("What's the difference between gingivitis and periodontitis?",
         "Gingivitis is gum inflammation only — red, swollen, bleeding gums, but no permanent damage. Fully reversible with good home care. Periodontitis is the next stage: the inflammation has now caused bone loss around the tooth, creating periodontal pockets. Periodontitis can be stopped but not reversed; gingivitis can be."),
        ("What causes gum disease in the first place?",
         "Bacterial plaque sitting along the gumline that isn't disrupted by daily brushing and flossing. Risk factors that make some people more susceptible: smoking (major), uncontrolled diabetes, genetic predisposition, hormonal changes (pregnancy, menopause), certain medications, and poor diet. Plaque is the cause; the risk factors determine how aggressively your body reacts to it."),
    ],
    # ========== RESTORATION ==========
    "app/procedures/restoration/composite-fillings/page.tsx": [
        ("How long do composite fillings last?",
         "Composite fillings typically last 7–10 years with good care — some last longer, some need replacement sooner. Lifespan depends on the size of the filling, where it's located (back-tooth fillings on chewing surfaces wear faster than front-tooth fillings), your bite, and grinding habits. Regular check-ups catch any wear before it becomes a problem."),
        ("Are composite fillings better than silver (amalgam) fillings?",
         "Modern composite is comparable in strength to amalgam for small-to-medium fillings, with major aesthetic advantages: it matches your tooth color and bonds directly to the tooth (no mechanical wedging needed). For very large fillings or in high-stress molar areas, amalgam still has some advantages in durability — but we use composite for the vast majority of our cases."),
        ("Why are my teeth sensitive after getting a filling?",
         "Temporary sensitivity to hot and cold for 1–2 weeks after a filling is normal — the tooth is acclimating to the new restoration and the nerve is responding to the slight inflammation from the procedure. If sensitivity persists beyond a few weeks or if you feel pain when biting down, call us — we may need to adjust the bite or check for a deep cavity."),
        ("Can I replace my old silver fillings with composite?",
         "Yes, and we do this regularly — both for aesthetic reasons (tooth-colored replacement) and when an old amalgam has cracked, worn, or leaked. We remove the old filling, check for any decay underneath, and bond a new composite in its place. It's a single-visit procedure for most cases."),
        ("How long does a composite filling appointment take?",
         "Typically 30–60 minutes per filling, depending on size and location. We numb the tooth, remove decay, prepare the cavity, place the composite in layers (curing each layer with a special light), shape it to match your bite, then polish. You walk out with the restoration done — no second visit needed."),
        ("Will my filling match my tooth color exactly?",
         "Yes — we use a shade guide to select composite that matches your tooth color, and we can blend multiple shades for the most natural result. Within a year or two, slight differences can appear as your natural tooth shade changes — but the original match is typically very close to invisible."),
        ("Can a composite filling fall out?",
         "Rarely — composites bond chemically to your tooth, so they don't 'fall out' the way an old mechanical filling might. If a composite does fail, it's usually because of new decay at the edge, a cracked tooth around the filling, or a very large filling that breaks under bite stress. Regular check-ups catch problems before the filling fails."),
        ("How much does a composite filling cost?",
         "Most composite fillings at our practice run $200–$400 depending on size and number of surfaces involved. Dental insurance typically covers a significant portion. We provide an exact quote before starting work and verify insurance benefits ahead of time."),
    ],
    "app/procedures/restoration/crowns-caps/page.tsx": [
        ("How long do porcelain crowns last?",
         "Most porcelain crowns last 15–25 years with good care — some last 30+. Lifespan depends on the underlying tooth's health, your bite, grinding habits, and home care. The crown itself is durable porcelain; what fails first is usually the tooth structure underneath if a new cavity forms at the margin where crown meets tooth."),
        ("What's the difference between a crown and a cap?",
         "Nothing — they're two words for the same thing. 'Crown' is the technical term; 'cap' is the older everyday term. Some dental offices use one or the other; we use them interchangeably. A crown/cap covers the entire tooth above the gumline, restoring shape, size, and strength."),
        ("Why do I need a crown after a root canal?",
         "Root canals remove the inner pulp of the tooth, which leaves the remaining tooth structure brittle and prone to fracture. A crown encases the tooth and protects it from breaking under chewing forces. Most back-tooth root canals need a crown within a few months to prevent tooth loss; front teeth sometimes can be restored with just a filling."),
        ("Will my crown look like a natural tooth?",
         "Yes — modern all-porcelain crowns are shaped, sized, and shaded to match your existing teeth. Most patients can't tell their crown from their natural teeth in the mirror. We choose the shade together using a guide and review the final result before bonding."),
        ("Can a crown get a cavity?",
         "The crown itself can't — porcelain doesn't decay. But new decay can form at the margin where the crown meets the natural tooth, especially if you have gum recession exposing root surfaces. That's why we still check crowns at every cleaning visit and X-ray. Good home care prevents this from being a problem."),
        ("How long is the wait between the temporary crown and the permanent one?",
         "Typically about 2 weeks. At the first appointment we prepare the tooth, take a mold, and place a temporary. The lab fabricates your permanent crown during that 2-week period; we bond it at the second visit. CEREC same-day crowns skip this wait entirely — the permanent is milled in our office while you wait."),
        ("Will a crown feel different from my natural tooth?",
         "For the first few days, yes — your tongue notices a new shape and you may feel it when biting. Most patients adjust within a week. If the crown feels too tall (hits before other teeth when biting) or rocks against your other teeth, call us — we'll do a quick bite adjustment."),
        ("How much does a porcelain crown cost?",
         "Most porcelain crowns at our practice run $1,200–$1,800 depending on the tooth, material choice, and lab used. Dental insurance typically covers a substantial portion (often around 50%) when the crown is for a damaged tooth. We provide exact quotes and verify insurance benefits before starting."),
    ],
    "app/procedures/restoration/dentures-partial-dentures/page.tsx": [
        ("What's the difference between complete and partial dentures?",
         "Complete dentures replace all teeth in an arch — used when you have no remaining teeth on top or bottom. Partial dentures fill in gaps when some natural teeth remain; they typically clip onto adjacent teeth with metal or flexible clasps. Both are removable. If you still have some healthy teeth, partials let you preserve them."),
        ("What's the difference between conventional and immediate dentures?",
         "Conventional dentures are made after your teeth are removed and your gums have healed for 4–6 weeks — meaning you go without teeth during the healing period, but the final fit is more accurate. Immediate dentures are made in advance and placed the same day your teeth come out, so you never go without teeth — but they require more adjustments as your gums shrink during healing."),
        ("How long does it take to get used to dentures?",
         "Typically 2–4 weeks to feel comfortable with eating and speaking, and up to a few months for your muscles and tissues to fully adapt. Expect some soreness, increased saliva flow, and difficulty with certain words during the first weeks. We do follow-up adjustments at 1 week, 1 month, and 3 months to refine the fit."),
        ("How long do dentures last?",
         "Most dentures last 5–10 years before needing replacement or significant rebasing — your jawbone and gum tissue change shape over time even without teeth, so the fit gradually changes. We typically do a reline (relining the inside surface to fit current tissue) every few years and replace the full denture around the 7–10 year mark."),
        ("Will I be able to eat normally with dentures?",
         "You'll learn a new way of eating, especially in the first few weeks. Start with soft foods cut into small pieces, then gradually add harder textures. Some foods stay challenging long-term (corn on the cob, whole apples, very chewy meats). Implant-supported dentures eliminate most chewing limitations — ask us if that's an option for your case."),
        ("Will my dentures look fake?",
         "Modern dentures are very natural-looking when done well. We custom-shape and shade the teeth to match your face and skin tone, and the gum-colored base is matched to your natural gum color. Most people in your life won't realize you're wearing dentures."),
        ("How do I clean my dentures?",
         "Brush them twice a day with a soft-bristled denture brush and mild soap or denture cleanser (not regular toothpaste — it's too abrasive). Soak them overnight in water or denture solution to keep them from drying out and warping. Rinse after every meal. Brush your gums and tongue too — they need cleaning even without teeth."),
        ("Are dental implants better than dentures?",
         "For chewing function and bone preservation, yes — implants stimulate the jawbone the way natural teeth do, while dentures don't, leading to gradual bone loss over time. For cost and surgical complexity, dentures win — they're typically much less expensive and require no surgery. Many patients do well with implant-supported dentures (the best of both)."),
        ("Will my speech be affected by dentures?",
         "Yes, especially in the first few weeks — words with 's', 'f', and 'th' sounds are typically the hardest to adjust to. Reading aloud at home for 15–20 minutes a day during the first 2 weeks accelerates the adjustment dramatically. Within a month, most patients speak normally."),
    ],
    "app/procedures/restoration/fixed-bridges/page.tsx": [
        ("What's the difference between a fixed bridge and a removable partial denture?",
         "A fixed bridge is cemented permanently to the natural teeth on either side of the gap — you can't take it out. A partial denture clips on and is removed daily for cleaning. Bridges feel and function more like natural teeth; partials are more cost-effective and reversible. For a single missing tooth between two healthy teeth, a bridge is usually the better long-term solution."),
        ("How long do dental bridges last?",
         "Most bridges last 10–15 years with good care, though many last 20+ years. The bridge itself is durable porcelain-fused-to-metal — what typically fails first is the natural anchor tooth underneath (new cavity at the margin, gum disease, or fracture). Regular check-ups catch any problems early."),
        ("Do the anchor teeth get damaged by the bridge?",
         "The anchor teeth (abutments) have to be filed down to receive the crown caps that hold the bridge in place — this preparation is permanent and means the anchor teeth always need crowns going forward. For this reason, when the anchor teeth are otherwise healthy, an implant may be a more conservative option than a bridge."),
        ("Can I floss with a bridge?",
         "Yes — but you can't slide regular floss between the bridge teeth (they're fused together). You use a floss threader (a soft plastic tool that loops floss under the bridge) or a water flosser to clean underneath the artificial tooth and around the anchor teeth. Daily cleaning under the bridge is essential to prevent gum disease and decay at the anchor margins."),
        ("How is a bridge different from a dental implant?",
         "A bridge anchors to your natural teeth on either side of the gap; an implant stands alone as an artificial tooth root in the jawbone. Bridges are faster (2–3 weeks vs. 4–9 months for an implant), require no surgery, and are usually less expensive — but they involve modifying healthy neighboring teeth. Implants preserve your other teeth and last longer."),
        ("Will the bridge look natural?",
         "Yes — modern porcelain bridges match the shape, size, and shade of your existing teeth. We choose the color together using a shade guide and review the result before final cementation. Most people can't tell a well-done bridge from natural teeth."),
        ("How long is the wait between the temporary bridge and the permanent one?",
         "Typically 2–3 weeks. At the first visit we prepare the anchor teeth, take a mold, and place a temporary bridge. The lab fabricates your permanent during that time; we cement it at the second visit. Sometimes we temporarily cement the permanent first to let you 'test drive' it for a few weeks before permanently bonding."),
        ("How much does a fixed bridge cost?",
         "A 3-unit bridge (2 anchor crowns + 1 artificial tooth) typically runs $3,000–$4,500 at our practice. Larger bridges (replacing multiple teeth) scale up from there. Dental insurance often covers a meaningful portion for medically necessary cases. We provide exact quotes and verify insurance ahead of time."),
    ],
}


def insert_faqs_into_file(path: str, faqs: list) -> bool:
    """Insert a faqs={[...]} block immediately before related={category.items}."""
    with open(path, encoding="utf-8") as f:
        content = f.read()

    if 'faqs={[' in content:
        print(f"SKIP (already has faqs): {path}")
        return False

    # Build the FAQ literal
    faq_lines = ["          faqs={["]
    for q, a in faqs:
        # escape backticks just in case
        qe = q.replace('"', '\\"')
        ae = a.replace('"', '\\"')
        faq_lines.append("            {")
        faq_lines.append(f'              q: "{qe}",')
        faq_lines.append(f'              a: "{ae}",')
        faq_lines.append("            },")
    faq_lines.append("          ]}")
    faq_block = "\n".join(faq_lines) + "\n          related={category.items}"

    old_anchor = "          related={category.items}"
    if old_anchor not in content:
        print(f"ERROR (no anchor): {path}")
        return False

    new_content = content.replace(old_anchor, faq_block, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"OK: {path} ({len(faqs)} FAQs)")
    return True


total = 0
applied = 0
for path, faqs in FAQS.items():
    total += 1
    if insert_faqs_into_file(path, faqs):
        applied += 1

print(f"\nApplied to {applied}/{total} pages")
