#!/usr/bin/env node
/**
 * Submit URLs to IndexNow — instant notification to Bing, Yandex, Seznam, Naver.
 * Google does NOT consume IndexNow (use GSC URL Inspection / sitemap crawl instead).
 *
 * Usage (run from project root):
 *   # Single or multiple URLs
 *   node scripts/indexnow-submit.mjs https://piedmontdentalbydesign.com/blog/new-post
 *
 *   # All URLs from the live sitemap.xml (fetched from SITE_URL/sitemap.xml)
 *   node scripts/indexnow-submit.mjs --sitemap
 *
 *   # All URLs from a local file (one per line)
 *   node scripts/indexnow-submit.mjs --file urls.txt
 *
 * Requires in .env.local:
 *   SITE_URL         Canonical site URL (https://piedmontdentalbydesign.com, no trailing slash)
 *   INDEXNOW_KEY     Key generated by generate-indexnow-key.mjs
 */

import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const args = process.argv.slice(2);
const urls = [];
let mode = "args"; // args | sitemap | file
let filePath = null;

for (let i = 0; i < args.length; i++) {
  if (args[i] === "--sitemap") mode = "sitemap";
  else if (args[i] === "--file" && args[i + 1]) {
    mode = "file";
    filePath = args[i + 1];
    i++;
  } else if (args[i].startsWith("http")) {
    urls.push(args[i]);
  }
}

// -- Load env ------------------------------------------------------------
function loadEnv() {
  const envPath = join(process.cwd(), ".env.local");
  let SITE_URL, INDEXNOW_KEY;
  try {
    const text = readFileSync(envPath, "utf8");
    for (const line of text.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const [key, ...rest] = trimmed.split("=");
      const value = rest.join("=").trim();
      if (key === "SITE_URL") SITE_URL = value;
      if (key === "INDEXNOW_KEY") INDEXNOW_KEY = value;
    }
  } catch {
    console.error(`Could not read ${envPath}. Create it with:`);
    console.error(`  SITE_URL=https://piedmontdentalbydesign.com`);
    console.error(`  INDEXNOW_KEY=<key from generate-indexnow-key.mjs>`);
    process.exit(1);
  }
  if (!SITE_URL || !INDEXNOW_KEY) {
    console.error("Missing SITE_URL or INDEXNOW_KEY in .env.local");
    process.exit(1);
  }
  return { SITE_URL: SITE_URL.replace(/\/$/, ""), INDEXNOW_KEY };
}

// -- Fetch URLs from sitemap ----------------------------------------------
async function fetchSitemap(siteUrl) {
  const sitemapUrl = `${siteUrl}/sitemap.xml`;
  console.log(`-> Fetching ${sitemapUrl}`);
  const res = await fetch(sitemapUrl);
  if (!res.ok) throw new Error(`Sitemap fetch failed: ${res.status}`);
  const xml = await res.text();
  // Pure-regex extraction -- no XML parser dep
  const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim());
  console.log(`-> Found ${urls.length} URLs in sitemap\n`);
  return urls;
}

// -- Submit batch -----------------------------------------------------------
async function submitBatch({ siteUrl, key, urls }) {
  // Verify host matches -- IndexNow rejects cross-host submission
  const host = new URL(siteUrl).host;
  for (const u of urls) {
    if (new URL(u).host !== host) {
      throw new Error(`URL host mismatch -- cannot submit ${u} from key file at ${host}`);
    }
  }

  const body = {
    host,
    key,
    keyLocation: `${siteUrl}/${key}.txt`,
    urlList: urls,
  };

  const res = await fetch("https://api.indexnow.org/indexnow", {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify(body),
  });

  return { status: res.status, text: await res.text() };
}

// -- Main ---------------------------------------------------------------
async function main() {
  const { SITE_URL, INDEXNOW_KEY } = loadEnv();

  let targetUrls = [];
  if (mode === "sitemap") {
    targetUrls = await fetchSitemap(SITE_URL);
  } else if (mode === "file") {
    const txt = readFileSync(resolve(process.cwd(), filePath), "utf8");
    targetUrls = txt
      .split("\n")
      .map((s) => s.trim())
      .filter((s) => s && s.startsWith("http"));
    console.log(`-> Loaded ${targetUrls.length} URLs from ${filePath}\n`);
  } else {
    targetUrls = urls;
    if (targetUrls.length === 0) {
      console.error("No URLs provided. Pass URLs as args, or use --sitemap, or --file <path>");
      process.exit(1);
    }
  }

  // IndexNow accepts up to 10,000 URLs per submission, but be conservative
  const BATCH_SIZE = 1000;
  let totalSubmitted = 0;
  let totalFailed = 0;

  for (let i = 0; i < targetUrls.length; i += BATCH_SIZE) {
    const batch = targetUrls.slice(i, i + BATCH_SIZE);
    console.log(`-> Submitting batch ${Math.floor(i / BATCH_SIZE) + 1} (${batch.length} URLs)...`);
    try {
      const { status, text } = await submitBatch({ siteUrl: SITE_URL, key: INDEXNOW_KEY, urls: batch });
      // IndexNow returns 200 (accepted), 202 (accepted, validation pending), 400/403/422 on errors
      if (status === 200 || status === 202) {
        console.log(`  OK HTTP ${status} -- ${batch.length} URLs accepted`);
        totalSubmitted += batch.length;
      } else {
        console.log(`  FAIL HTTP ${status} -- ${text}`);
        totalFailed += batch.length;
      }
    } catch (err) {
      console.log(`  FAIL ${err.message}`);
      totalFailed += batch.length;
    }
  }

  console.log(`\nDone. Submitted ${totalSubmitted}, failed ${totalFailed}.`);
  if (totalSubmitted > 0) {
    console.log(`\nNote: HTTP 200/202 means IndexNow accepted the submission, NOT that pages are indexed.`);
    console.log(`Bing typically processes within minutes; check BWT -> URL Inspection to confirm.`);
  }
  if (totalFailed > 0) {
    console.log(`\nCommon causes for failure:`);
    console.log(`  - 403: key file not reachable at ${SITE_URL}/${INDEXNOW_KEY}.txt -- verify with curl`);
    console.log(`  - 422: URL host doesn't match the key host`);
    console.log(`  - 400: malformed body (rare with this script)`);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Fatal:", err.message);
  process.exit(1);
});
